global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'customer_service'
      metrics_path: '/actuator/prometheus'
      scape_interval: 5s
      static_configs:
          - targets: ['172.31.96.1:8081']
            labels:
              application: 'Customer Service App'